### PR TITLE
[CS][91144282] Update cluster opts to mixin + tests

### PR DESCRIPTION
**Pull request by wolves**
https://www.pivotaltracker.com/story/show/91144282

### CODE REVIEW

**Comment by pasha** [comment]
:+1: i only runned tests

**Comment by warrenv** [comment]
Almost there, tests pass but it looks like 'npm run build' was not done before pushing.
Running 'npm run watch' in another window helps with this.
It also helps to run 'npm run preversion' as a sanity check right before pushing. It takes a little longer but will make sure dependencies are up to date, tests pass and the dist/ is up to date.

**Comment by pasha** [comment]
Thanks for the info @warrenv , i didn't know about 'npm run preversion'

**Comment by warrenv** [comment]
np. I usually 'hub checkout' the PR and then just run that.

**Comment by Teapane** [comment]
:+1: `npm preversion`

**Pull request merged**
