### PR TITLE
[MTS/TL][87765368] Add testing framework

### PR DESCRIPTION
**Pull request by michaelstalker**
https://www.pivotaltracker.com/story/show/87765368

### CODE REVIEW

**Comment by luketower** [comment]
:+1:

**Comment by davidcole** [comment]
Nice! :+1:

**Comment by Teapane** [comment]
:+1:

**Comment by c0** [comment]
Can we [resolve the jquery version in `bower.json`](https://github.com/bower/bower.json-spec#resolutions)?

```
Unable to find a suitable version for jquery, please choose one:
    1) jquery#1.8.3 which resolved to 1.8.3 and is required by flight#1.0.11
    2) jquery#* which resolved to 2.1.3 and is required by map, primedia_events#0.0.6
    3) jquery#>=2 which resolved to 2.1.3 and is required by jasmine-jquery#2.0.6
```

**Pull request merged**
