### PR TITLE
[GI/EH] [69482862] Fetch listings once on first render

### PR DESCRIPTION
**Pull request by rawsyntax**
[PT#69482862](https://www.pivotaltracker.com/n/projects/1054862/stories/69482862)

Example url: http://local.apartmentguide.com/map?state=Virginia&city=Arlington&neighborhood=Virginia-Highlands&refinements=1-beds-1z141xt

### CODE REVIEW

**Comment by pasha** [comment]
:+1:

**Comment by c0** [comment]
This issue is definitely tricky. This feels more like a patch around how event listeners are attached to google maps.

It looks like the issue lies in that google fires the idle event twice (line #58). This means that both `fireOurMapEventsOnce` and `handleOurMapEvents` are called twice.

``` coffee
  google.maps.event.addListenerOnce @attr.gMap, 'idle', =>
    @fireOurMapEventsOnce()
    @handleOurMapEvents()
```

**Comment by rawsyntax** [comment]
This is a quick fix -- I think the best approach would be to rewrite this with tests from the ground up, but that would have taken way more time.  As it sits, it is very difficult to trace what is going on.

**Comment by c0** [comment]
@rawsyntax I agree and it could use a good refactoring. IMO, attaching events to google maps needs to be consolidated.

**Comment by pasha** [comment]
Agree with Eric, and i take full responsibility for not having any tests for the map library.  There a lot of things that could be improved.

**Comment by pasha** [comment]
:+1: for the quick fix

**Pull request merged**
