### PR TITLE
M.AG: Update precision for map page Geo

### PR DESCRIPTION
**Pull request by tb0yd**
https://www.pivotaltracker.com/story/show/77211148

### CODE REVIEW

**Comment by pasha** [comment]
we already did similar thing for big web, any idea why it's not working? https://github.com/primedia/map.js/blob/dev/src/data/listings.coffee#L88

**Comment by cdemyanovich** [comment]
I agree with @pasha. What's more, we're rounding to the nearest integer in the code he referenced. Why are we truncating to 4 decimal places here?

Also, if this change is to be kept, it would be good to allow an override in case any other code has a reason to prefer a different limit. See: https://github.com/primedia/map.js/blob/02bc7927eac639f0971498410c6ddaac2971575a/src/utils/map_utils.coffee#L11.

**Comment by tb0yd** [comment]
The fix you linked won't have an effect because it's not used.

https://github.com/primedia/m.apartmentguide/blob/dev/app/assets/javascripts/listings_markers.js.coffee#L62

Craig, I didn't realize you had already solved the problem in another place. I just went directly to the "distance_conversion" file and changed it. I didn't do a general survey of the map.js code. My mistake.

**Comment by tb0yd** [comment]
I think I will go and change the code in mdot to use Math.round().

**Comment by cdemyanovich** [comment]
@tb0yd No worries. I think using `Math.round()` is the right thing to do. And, I think AG and m.AG _might_ be the right place to do it. That way, all the other code in map.js that computes distances and radii incurs no rounding or truncation. But, if this change is needed in many apps, then I think it's worth revisting map.js for a good place to put it.

**Comment by tb0yd** [comment]
Cool. Thanks, glad you guys caught this.

**Pull request closed without merging**
